# -*- coding: utf-8 -*-
"""Apriori Association Rule Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pqudNSepAF8o_f31rOzSZAy7k1YsowXt

# Apriori
"""

!pip install apyori

"""## Importing libraries"""

import pandas as pd
import numpy as np
import matplotlib as plt
import matplotlib.pyplot as plt

"""## Importing dataset"""

dataset = pd.read_csv('/content/Big Basket.com Cart Apriori.csv' , header = None )
transactions = []

for i in range(0,7219):
  transactions.append([str(dataset.values[i, j]) for j in range(0, 20)])

print(transactions)

"""## Apriori Training on Dataset"""

from apyori import apriori
basket_intelligence = apriori(transactions = transactions, min_support = 0.002, min_confidence = 0.2, min_lift = 3, min_len = 2)

"""## Visualizing"""



"""### Raw Results"""

results = list(basket_intelligence)
results

"""### Proper Display"""

def inspect(results):
    product1         = [tuple(result[2][0][0])[0] for result in results]
    product2         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(product1, product2, supports, confidences, lifts))
DataFrame_intelligence = pd.DataFrame(inspect(results), columns = ['product1', 'product1', 'Support', 'Confidence', 'Lift'])

DataFrame_intelligence

DataFrame_intelligence.nlargest(n = 10, columns = 'Lift')