# -*- coding: utf-8 -*-
"""Eclat Association Rule Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tuWnatnQXmOSM1wl163voskVyjPZCAj8

# Eclat

#the differnce between apriori and eclat is first eclat is simpler and in eclat the obeservation is dividen into sets, there is no lift or confidence, 2 objects are present instead of one

## Importing libraries
"""

import pandas as pd
import numpy as np
import matplotlib as plt
import matplotlib.pyplot as plt

!pip install apyori

"""## Importing dataset"""

dataset = pd.read_csv('/content/Netflix Movie Recommendation.csv' , header = None )
transactions = []

for i in range(0,7466):
  transactions.append([str(dataset.values[i, j]) for j in range(0, 20)])

"""## Eclat Training on Dataset"""

from apyori import apriori
rules = apriori(transactions = transactions, min_support = 0.002, min_confidence = 0.2, min_lift = 3, min_len = 2)

"""## Visualizing

### Raw Results
"""

results = list(rules)

results

"""### Proper Display"""

def inspect(results):
    movie1         = [tuple(result[2][0][0])[0] for result in results]
    movie2         = [tuple(result[2][0][1])[0] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(movie1, movie2, lifts))
DataFrame_intelligence = pd.DataFrame(inspect(results), columns = ['movie1', 'movie2',  'Lift'])

DataFrame_intelligence

DataFrame_intelligence.nlargest(n = 10, columns = 'Lift')